name: Python Guess Number Game application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Create Virtual Environment and activate
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        python -m virtualenv projectenv
        source projectenv/bin/activate
        which python
    - name: Install dependencies
      run: | 
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build and Push Container to ghcr.io
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}  # it will be lowercased internally
        github_token: ${{ secrets.GITHUB_TOKEN }}
        image_tag: latest